---
version: '2.1'
services:
  gemstash:
    build:
      context: .
      dockerfile: Dockerfile
    # image: zappi/gemstash:1.2.0
    environment:
      RACK_ENV: production
    ports:
      - 9292:9292

volumes:
  gemstash_data:
    driver: local
