---
version: '2.1'
services:
  gemstash:
    build: .
    image: zappi/gemstash:latest
    environment:
      RACK_ENV: production
    ports:
      - 9292:9292
    volumes:
      - gemstash_data:/home/gemstash/data

volumes:
  gemstash_data:
    driver: local
